title: Intro Sistemas Inteligentes 2025-1
description: Universidad Nacional de Colombia, Bogotá
sitename: Intro Sistemas Inteligentes
baseurl: '/iis-2025-1'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
